apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: MTcyLjI3LjEwNy4zMQ==         
  DB_USER: cm9vdA==                   
  DB_PASSWORD: U2Fuc2tydXRpQDEyMw==    
  DB_NAME: aW50ZXJuc2hpcF9kYg==        
